name: usedmoa
description: 중고모아 프로젝트.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0 # 참고: https://pub.dev/packages/provider/install
  http: ^0.13.3 # 참고: https://pub.dev/packages/http/install
  carousel_slider: ^4.0.0 # 참고: https://pub.dev/packages/carousel_slider/install
  image_picker: ^0.8.3+2 # 참고: https://pub.dev/packages/image_picker/install
  web3dart: ^2.3.1 # 참고: https://pub.dev/packages/web3dart
  permission_handler: ^8.1.1
  sqflite: ^2.0.0+4 # 참고: https://pub.dev/packages/sqflite/install
  path_provider: ^2.0.2 # 참고: https://pub.dev/packages/path_provider/install
  flutter_bloc: ^7.2.0 # 참고: https://pub.dev/packages/flutter_bloc/install
  shared_preferences: ^2.0.7 # 참고: https://pub.dev/packages/shared_preferences/install
  bloc: ^7.1.0 # 참고: https://pub.dev/packages/bloc/install
  equatable: ^2.0.3 # 참고: https://pub.dev/packages/equatable/install
  flutter_kakao_login: ^3.4.0 # https://pub.dev/packages/flutter_kakao_login/install
  kakao_flutter_sdk: ^0.7.1 # https://pub.dev/packages/kakao_flutter_sdk/install
  flutter_dotenv: ^5.0.2 # https://pub.dev/packages/flutter_dotenv/install
  datetime_picker_formfield: ^2.0.0 # https://pub.dev/packages/datetime_picker_formfield/install
  cached_network_image: ^3.1.0 # https://pub.dev/packages/cached_network_image/install
  flutter_inappwebview: ^5.3.2
  html: 0.14.0+3
  freezed_annotation:
  build_runner:
  url_launcher:
  video_player:
  dio:
  json_annotation:
  platform:
  package_info:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:

flutter:

  # true 로 되어 있어야 미리 정의된 머티리얼 아이콘 세트를 사용가능
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mountain.jpg
    - assets/images/offline_icon.png
    - assets/images/openvidu_logo.png
    - assets/icons/notification.png
    - assets/icons/search.png
    - assets/abi/erc20_abi.json
    - assets/abi/erc1155_abi.json
    - .env